# Generated by Django 4.2.3 on 2023-07-17 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
