# Generated by Django 4.2.2 on 2023-06-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_remove_user_first_name_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
