# Generated by Django 4.2.2 on 2023-06-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_address', models.CharField(blank=True, max_length=2500)),
                ('address', models.CharField(blank=True, max_length=2500)),
                ('stamp', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=2500)),
                ('header', models.CharField(blank=True, max_length=2500)),
                ('opener', models.CharField(blank=True, max_length=2500)),
                ('body', models.CharField(blank=True, max_length=2500)),
                ('closer', models.CharField(blank=True, max_length=2500)),
                ('signature', models.CharField(blank=True, max_length=2500)),
                ('postscript', models.CharField(blank=True, max_length=2500)),
            ],
        ),
    ]
