# Generated by Django 4.2.2 on 2023-06-07 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='draft', max_length=25),
        ),
        migrations.AddField(
            model_name='letter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
