# Generated by Django 4.2.2 on 2023-06-07 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_letter_options_letter_created_at_letter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='return_address',
            field=models.CharField(blank=True, max_length=2500, verbose_name='Return Address'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='closer',
            field=models.CharField(blank=True, help_text='Regards,', max_length=2500),
        ),
        migrations.AlterField(
            model_name='letter',
            name='opener',
            field=models.CharField(blank=True, help_text='Dear [name],', max_length=2500),
        ),
        migrations.AlterField(
            model_name='letter',
            name='postscript',
            field=models.CharField(blank=True, help_text='P.S. [message]', max_length=2500),
        ),
    ]
