# Generated by Django 4.2.3 on 2023-07-17 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message='Zip code must be exactly 5 digits', regex='^[0-9]{5}$')]),
        ),
    ]
