# Generated by Django 4.2.2 on 2023-06-08 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=2500)),
                ('header', models.CharField(blank=True, max_length=2500)),
                ('opener', models.CharField(blank=True, help_text='Dear [name],', max_length=2500)),
                ('body', models.CharField(blank=True, max_length=2500)),
                ('closer', models.CharField(blank=True, help_text='Regards,', max_length=2500)),
                ('signature', models.CharField(blank=True, max_length=2500)),
                ('postscript', models.CharField(blank=True, help_text='P.S. [message]', max_length=2500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='draft', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_letters', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_address', models.CharField(blank=True, max_length=2500, verbose_name='Return Address')),
                ('address', models.CharField(blank=True, max_length=2500)),
                ('stamp', models.CharField(blank=True, max_length=2500)),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letter.letter')),
            ],
        ),
    ]
