# Generated by Django 4.2.2 on 2023-06-08 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={},
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='created_at',
        ),
    ]
