# Generated by Django 4.2.2 on 2023-06-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0002_alter_letter_options_remove_envelope_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='closer',
            field=models.CharField(blank=True, help_text='Regards,', max_length=2500, verbose_name='Complimentary close'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
